replicaCount: 1
image:
  repository: ghcr.io/shareify-project/shareify-review-service
  pullPolicy: IfNotPresent
  tag: "v1.1.1"
service:
  type: ClusterIP
  port: 8000
persistence:
  size: 1Gi
  storageClass: "csi-standard"
  mountPath: /data
env:
  databasePath: "/data/reviews.db"
